#!/usr/bin/guile -s
coding: utf-8
!#

;; Copyright (C) 2020 Solène Husseini solene.husseini@gmail.com
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.# 
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

(use-modules 
    (ice-9 textual-ports)
    (srfi srfi-1))

(define (convert text)
    (filter 
        (lambda (l) 
            (not 
                (equal? l (list ""))))
        (map 
            (lambda (s) (string-split s #\,)) 
            (string-split text #\newline))))

(define (to-html lss)
    (string-append
        "<table>\n"
        (fold
            (lambda (ls acc)
                (string-append
                    acc
                    "<tr>\n"
                    (fold
                        (lambda (x acc) (string-append acc "<td>" x "</td>\n"))
                        ""
                        ls)
                    "</tr>\n"))
            ""
            lss)
        "</table>\n"))

(define (default-style)
    "<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }
    </style>\n")

(let 
    ((s 
        (convert 
            (get-string-all 
                (current-input-port)))))
    
    #! (write s) !#
    (display
        (string-append
            (default-style)
            (to-html s)))
)

